using UnityEngine;
using VContainer;
using TownsPeople.UI;
using TownsPeople.Data;
using TownsPeople.Services;
using TownsPeople.GamePlay;

namespace TownsPeople.GamePlay
{
    /// <summary>
    /// Lightweight, standalone greeting behavior: reacts to the player with a Positive or
    /// Negative response pulled from a GeneralRumorResponseLibrary, chosen by this NPC's
    /// current effective reputation reading of the player (same selection logic
    /// NPCGossipMemory uses for its own fallback tier), using this NPC's Voice Gender for
    /// audio. Completely independent of the rumor/gossip system — usable on its own (e.g. a
    /// "Non-Dialogue" NPC generated by the wizard) or alongside NPCGossipMemory as its
    /// fallback greeting when no rumor is currently pending.
    /// </summary>
    public class NPCGreetingResponder : MonoBehaviour
    {
        [Tooltip("Shared library of generic Positive/Negative reactions this NPC greets the player with.")]
        [SerializeField] private GeneralRumorResponseLibrary _responseLibrary;

        [Tooltip("Which gendered voice line this NPC uses for greeting audio that provides both a Male and Female clip.")]
        [SerializeField] private VoiceGender _voiceGender = VoiceGender.Male;

        [Header("Presentation Dependencies (auto-resolved if left empty)")]
        [SerializeField] private NPCSpeechBubble _speechBubble;
        [SerializeField] private AudioSource _audioSource;

        private NPCReputationOpinion _reputationOpinion;
        private ReputationService _reputationService;

        // v2: Track this NPC's own last-used index per pool, so consecutive greetings don't
        // repeat the same line back to back. Deliberately per-instance (not shared across
        // NPCs, and not stored on the library asset itself).
        private int _lastPositiveIndex = -1;
        private int _lastNegativeIndex = -1;

        [Inject]
        public void Construct(ReputationService reputationService)
        {
            _reputationService = reputationService;
        }

        private void Awake()
        {
            if (_speechBubble == null) _speechBubble = GetComponentInChildren<NPCSpeechBubble>();
            if (_audioSource == null) _audioSource = GetComponent<AudioSource>();
            _reputationOpinion = GetComponent<NPCReputationOpinion>();
        }

        /// <summary>
        /// Greets the player right now: picks a response from the Positive or Negative pool
        /// (based on this NPC's current standing reading of the player) and presents it —
        /// text bubble plus the gendered audio clip, if any.
        /// </summary>
        public void PlayGreeting()
        {
            if (_responseLibrary == null)
            {
                Debug.LogWarning($"<color=orange>[NPCGreetingResponder]</color> '{gameObject.name}' has no Response Library assigned.", this);
                return;
            }

            RumorAlignment standing = GetPlayerStandingAlignment();
            RumorResponse? response = standing == RumorAlignment.Positive
                ? _responseLibrary.GetRandomResponse(standing, ref _lastPositiveIndex)
                : _responseLibrary.GetRandomResponse(standing, ref _lastNegativeIndex);

            if (response == null)
            {
                Debug.LogWarning($"<color=orange>[NPCGreetingResponder]</color> '{gameObject.name}' has no responses in the '{standing}' pool.", this);
                return;
            }

            if (_responseLibrary.ShowTextBubble && _speechBubble != null && !string.IsNullOrEmpty(response.Value.ResponseText))
            {
                _speechBubble.DisplayText(response.Value.ResponseText);
            }

            AudioClip clip = response.Value.GetVoiceLine(_voiceGender);
            if (clip != null && _audioSource != null)
            {
                _audioSource.clip = clip;
                _audioSource.Play();
            }
        }

        /// <summary>
        /// This NPC's read on the player's current standing — its own NPCReputationOpinion if
        /// present, otherwise just the shared general reputation.
        /// </summary>
        private RumorAlignment GetPlayerStandingAlignment()
        {
            float effectiveReputation = _reputationOpinion != null
                ? _reputationOpinion.GetEffectiveReputation()
                : (_reputationService != null ? _reputationService.GetGeneralReputation() : 0f);

            return effectiveReputation >= 0f ? RumorAlignment.Positive : RumorAlignment.Negative;
        }

        /// <summary>
        /// Forces this NPC's speech bubble to fade out immediately, interrupting whatever it's
        /// currently doing. Called by NPCProximityGossip when the player walks away.
        /// </summary>
        public void HideSpeechBubble()
        {
            _speechBubble?.HideImmediately();
        }
    }
}